
import React from 'react';
import Button from '../components/Button';
import { Link } from 'react-router-dom';

function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center  py-20 px-2">
      <div className="w-full max-w-8xl  p-12 flex flex-col md:flex-row items-center gap-12">
        {/* Left: Hero Text and Features */}
        <div className="flex-1 flex flex-col gap-10">
          <div className="mb-2">
            <h1 className="text-5xl font-extrabold text-blue-700 mb-4 leading-tight">AI Notetaker</h1>
            <p className="text-lg text-gray-600 mb-2">Your smart assistant for <span className="text-blue-600 font-semibold">meeting notes</span> and <span className="text-cyan-600 font-semibold">AI-powered summaries</span>.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-6 shadow-sm flex flex-col gap-2">
              <span className="font-bold text-blue-600 text-lg">Upload Transcript</span>
              <span className="text-gray-700 text-base">Easily upload your meeting or call notes as a text file.</span>
            </div>
            <div className="bg-cyan-50 border border-cyan-200 rounded-xl p-6 shadow-sm flex flex-col gap-2">
              <span className="font-bold text-cyan-600 text-lg">Custom Prompts</span>
              <span className="text-gray-700 text-base">Guide the AI with your own instructions for tailored summaries.</span>
            </div>
            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm flex flex-col gap-2">
              <span className="font-bold text-gray-700 text-lg">AI Summaries</span>
              <span className="text-gray-700 text-base">Get structured, editable summaries generated by AI.</span>
            </div>
            <div className="bg-gray-50 border border-gray-200 rounded-xl p-6 shadow-sm flex flex-col gap-2">
              <span className="font-bold text-gray-600 text-lg">Share Easily</span>
              <span className="text-gray-700 text-base">Send your summary via email to anyone, instantly.</span>
            </div>
          </div>
        </div>
        {/* Right: Illustration */}
        <div className="flex-1 flex items-center justify-center">
          <img
            src="https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YWl8ZW58MHwwfDB8fHww"
            alt="AI Notetaker Illustration"
            className="rounded-2xl shadow-lg w-full max-w-xs md:max-w-2xl border border-blue-100"
            loading="lazy"
          />
        </div>
      </div>
      <Link to={'upload'}>
      <Button text={"Get Started For Free"}/>
      </Link>
    </main>
  );
}

export default Home;